Mvc.Grid/Mvc.Grid/Models/Adres.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace Mvc.Grid.Models
{
    [Table("Adresler")]
    public class Adres
    {
     [Key,DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int Id { get; set; }
        public string Ad { get; set; }
    }
}

Mvc.Grid/Mvc.Grid/Models/Manager/DatabaseContext.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;

namespace Mvc.Grid.Models.Manager
{
    public class DatabaseContext:DbContext
    {
        public DbSet<Personel> Personeller { get; set; }
        public DbSet<Ulke> Ulkeler { get; set; }

        public DbSet<Adres> Adresler { get; set; }

        public DatabaseContext()
        {
            Database.SetInitializer<DatabaseContext>(new Olusturucu());
        }
        
    }


    public class Olusturucu:CreateDatabaseIfNotExists<DatabaseContext>
    {
        protected override void Seed(DatabaseContext context)
        {
            List<Ulke> ulkeList = new List<Ulke>();
            for (int i = 0; i < 10; i++)
            {
                Ulke ulke = new Ulke();
                ulke.Ad = FakeData.PlaceData.GetCountry();
                ulkeList.Add(ulke);
                context.Ulkeler.Add(ulke);
            }
            context.SaveChanges();

            for (int i = 0; i < 100; i++)
            {
                Personel per = new Personel();
                per.Ad = FakeData.NameData.GetFirstName();
                per.Soyad = FakeData.NameData.GetSurname();
                per.Yas = FakeData.NumberData.GetNumber(10, 90);

                Random r = new Random();
                int deger = r.Next(0, 10);
                per.Ulke = ulkeList[deger];
                context.Personeller.Add(per);
            }
            context.SaveChanges();
        }
    }
}

Mvc.Grid/Mvc.Grid/Models/Personel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace Mvc.Grid.Models
{
    [Table("Personeller")]
    public class Personel
    {
        [Key,DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int Id { get; set; }
        [StringLength(50),Required]
        public string Ad { get; set; }
        public string Soyad { get; set; }
        public int Yas { get; set; }
        public Ulke Ulke { get; set; } //bir personelin 1 ülkesi olabilir
    }
}

Mvc.Grid/Mvc.Grid/Models/Ulke.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace Mvc.Grid.Models
{
    [Table("Ulkeler")]
    public class Ulke
    {
        [Key, DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int Id { get; set; }
        public string Ad { get; set; }
        public List<Personel> Personeller { get; set; } //bir ülkede birden fazla personel olabilir
    }
}

Mvc.Grid/Mvc.Grid/Controllers/GridController.cs
using Mvc.Grid.Models;
using Mvc.Grid.Models.Manager;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Mvc.Grid.Controllers
{
    public class GridController : Controller
    {
        DatabaseContext db = new DatabaseContext();
        // GET: Grid
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult Listele()
        {
            var model = db.Personeller.ToList();
            return View(model);
        }
        public ActionResult Ekle()
        {
            List<SelectListItem> ulkeler =
                (from i in db.Ulkeler.ToList()
                 select new SelectListItem
                 {
                     Text = i.Ad,
                     Value = i.Id.ToString()

                 }
                 ).ToList();
            ViewBag.Ulkeler = ulkeler;   
            return View();
        }

        [HttpPost]
        public ActionResult Ekle(Personel model)
        {
            var ulke = db.Ulkeler.Where(m => m.Id == model.Ulke.Id).FirstOrDefault();

            model.Ulke = ulke;
            db.Personeller.Add(model);
            db.SaveChanges();
            return RedirectToAction("Listele");
            
        }

        public ActionResult Duzenle(int id)
        {
            var personel = db.Personeller.Where(m => m.Id == id).FirstOrDefault();
            List<SelectListItem> ulkeler =
                (from i in db.Ulkeler.ToList()
                 select new SelectListItem
                 {
                     Text = i.Ad,
                     Value = i.Id.ToString()

                 }
                 ).ToList();
            ViewBag.Ulkeler = ulkeler;
            return View(personel);
        }



        [HttpPost]
        public ActionResult Duzenle(Personel model)
        {
            var personel = db.Personeller.Where(m => m.Id ==model.Id).FirstOrDefault();
            personel.Ad = model.Ad;
            personel.Soyad = model.Soyad;
            personel.Yas = model.Yas;
            var ulke = db.Ulkeler.Where(m => m.Id == model.Ulke.Id).FirstOrDefault();
            personel.Ulke = ulke;
            db.SaveChanges();
            return RedirectToAction("Listele");

        }

        public ActionResult Sil(int? id)
        {
            var personel = db.Personeller.Where(m => m.Id ==id).FirstOrDefault();
            if (personel!=null)
            {
                db.Personeller.Remove(personel);
                int deger = db.SaveChanges(); //veri tabanında etkilenen satır sayısını tutar
                if (deger>0)
                {
                    //veri tabanı etkilendi
                }
                else
                {
                    //veri tabanı etkilenmedi
                }
            }
            return View();
        }



    }
}

Mvc.Grid/Mvc.Grid/Controllers/HomeController.cs
using Mvc.Grid.Models.Manager;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Mvc.Grid.Controllers
{
    public class HomeController : Controller
    {
        DatabaseContext db = new DatabaseContext();
        // GET: Home
        public ActionResult Index()
        {
            var model = db.Personeller.ToList();
            return View();
        }
        public ActionResult Listele()
        {
            var model = db.Personeller.ToList();
            return View(model); //modeli viewimize yolluyoruz
        }
    }
}

Mvc.Grid/Mvc.Grid/Views/Grid/Duzenle.cshtml
@model Mvc.Grid.Models.Personel
@{
    ViewBag.Title = "Duzenle";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Duzenle</h2>

@using (Html.BeginForm())
{

    <div class="input-group">
        <span class="input-group-addon" id="txt_soyad"><i class="glyphicon glyphicon-user"></i></span>
        @Html.TextBoxFor(m => m.Ad, new { @class = "form_control", placeholder = "Adını Giriniz", aria_describedy = "txt_ad" })
    </div>
    <br />



    <div class="input-group">
        <span class="input-group-addon" id="txt_soyad"><i class="glyphicon glyphicon-user"></i></span>
        @Html.TextBoxFor(m => m.Soyad, new { @class = "form_control", placeholder = "Soyadını Giriniz", aria_describedy = "txt_soyad" })
    </div>
    <br />

    <div class="input-group">
        <span class="input-group-addon" id="txt_yas"><i class="glyphicon glyphicon-time"></i></span>
        @Html.TextBoxFor(m => m.Yas, new { @class = "form_control", placeholder = "Yaşını Giriniz", aria_describedy = "txt_yas" })
    </div>
    <br />

    <div class="input-group">
        <span class="input-group-addon" id="txt_ulke"><i class="glyphicon glyphicon-globe"></i></span>
        @Html.DropDownListFor(m => m.Ulke.Id, (List<SelectListItem>)ViewBag.Ulkeler, new { @class = "form_control", aria_describedy = "txt_ulke" })
    </div>
    <br />

    <input type="submit" class="btn btn-success" value="Kaydet" />
    @Html.HiddenFor(m=>m.Id)

}

Mvc.Grid/Mvc.Grid/Views/Grid/Ekle.cshtml
@model Mvc.Grid.Models.Personel
@{
    ViewBag.Title = "Ekle";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Ekle</h2>
@using (Html.BeginForm())
{

<div class="input-group">
    <span class="input-group-addon" id="txt_soyad"><i class="glyphicon glyphicon-user"></i></span>
    @Html.TextBoxFor(m => m.Ad, new { @class = "form_control", placeholder = "Adını Giriniz", aria_describedy = "txt_ad" })
</div>
    <br />



    <div class="input-group">
        <span class="input-group-addon" id="txt_soyad"><i class="glyphicon glyphicon-user"></i></span>
        @Html.TextBoxFor(m => m.Soyad, new { @class = "form_control", placeholder = "Soyadını Giriniz", aria_describedy = "txt_soyad" })
    </div>
    <br />

    <div class="input-group">
        <span class="input-group-addon" id="txt_yas"><i class="glyphicon glyphicon-time"></i></span>
        @Html.TextBoxFor(m => m.Yas, new { @class = "form_control", placeholder = "Yaşını Giriniz", aria_describedy = "txt_yas" })
    </div>
    <br />

    <div class="input-group">
        <span class="input-group-addon" id="txt_ulke"><i class="glyphicon glyphicon-globe"></i></span>
        @Html.DropDownListFor(m => m.Ulke.Id, (List<SelectListItem>)ViewBag.Ulkeler, new { @class = "form_control", aria_describedy = "txt_ulke" })
    </div>
    <br />

    <input type="submit" class="btn btn-success" value="Kaydet" />
}

Mvc.Grid/Mvc.Grid/Views/Grid/Listele.cshtml
@model IEnumerable<Mvc.Grid.Models.Personel>
@using GridMvc.Html
@{
    ViewBag.Title = "Listele";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Listele</h2>
@Html.ActionLink("Ekle", "Ekle", "Grid", null,new{@class="btn btn-primary"})
@Html.Grid(Model).Columns(column=>
{
    column.Add(m => m.Ad).Titled("Adlar").Sortable(true).Filterable(true);
    column.Add(m => m.Soyad).Titled("Soyadlar").Sortable(true).Filterable(true);
    column.Add(m => m.Yas).Titled("Yaslar").Sortable(true).Filterable(true);
    column.Add()
    .Encoded(false)
    .Sanitized(false) //hassas veri temizleme olmasın
    .SetWidth(30)
    .RenderValueAs(o => Html.ActionLink( "Düzenle","Duzenle","Grid",new {id=o.Id}, new {@class="btn btn-warning"}));
    column.Add()
   .Encoded(false)
   .Sanitized(false) //hassas veri temizleme olmasın
   .SetWidth(30)
   .RenderValueAs(o => Html.ActionLink("Sil", "Sil", "Grid", new { id = o.Id }, new { @class = "btn btn-danger" }));
}).WithPaging(10)

Mvc.Grid/Mvc.Grid/Views/Grid/Sil.cshtml
@{
    ViewBag.Title = "Sil";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Sil</h2>

@Html.ActionLink("Listele", "Listele", "Grid", null, new { @class="btn btn-warning"})

Mvc.Grid/Mvc.Grid/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

Mvc.Grid/Mvc.Grid/Views/Home/Listele.cshtml
@model IEnumerable<Mvc.Grid.Models.Personel>
@{
    ViewBag.Title = "Listele";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Personelleri Listele</h2>
<ul class="list-group">
   @foreach(var item in Model)
   {
       <li class="list-group-item">
           @item.Ad
    

       </li>
   }
</ul>

Mvc.Grid/Mvc.Grid/Views/Shared/_Grid.cshtml
@using GridMvc.Columns
@model GridMvc.IGrid
@if (Model == null) { return; }
@if (Model.RenderOptions.RenderRowsOnly)
{
    @RenderGridBody();
}
else
{
    <div class="grid-mvc" data-lang="@Model.Language" data-gridname="@Model.RenderOptions.GridName" data-selectable="@Model.RenderOptions.Selectable.ToString().ToLower()" data-multiplefilters ="@Model.RenderOptions.AllowMultipleFilters.ToString().ToLower()">
        <div class="grid-wrap">
            <table class="table table-striped grid-table">
                @* Draw grid header *@
                <thead>
                    @RenderGridHeader()
                </thead>
                <tbody>
                    @RenderGridBody()
                </tbody>
            </table>
            @RenderGridPager()
        </div>
    </div>
}
@helper RenderGridBody()
{
    if (!Model.ItemsToDisplay.Any())
    {
    <tr class="grid-empty-text">
        <td colspan="@Model.Columns.Count()">
            @Model.EmptyGridText
        </td>
    </tr>
    }
    else
    {
        foreach (object item in Model.ItemsToDisplay)
        {
    <tr class="grid-row @Model.GetRowCssClasses(item)">
        @foreach (IGridColumn column in Model.Columns)
        {
            @column.CellRenderer.Render(column, column.GetCell(item))
        }
    </tr>
        }
    }
}
@helper RenderGridHeader()
{
    <tr>
        @foreach (IGridColumn column in Model.Columns)
        {
            @column.HeaderRenderer.Render(column)
        }
    </tr>
}
@helper RenderGridPager()
{
    if (Model.EnablePaging && Model.Pager != null)
    {
    <div class="grid-footer">
        @Html.Partial(Model.Pager.TemplateName, Model.Pager)
    </div>
    }
}

Mvc.Grid/Mvc.Grid/Views/Shared/_GridPager.cshtml
@model GridMvc.Pagination.GridPager
@if (Model == null || Model.PageCount <= 1)
{
    return;
}
<div class="grid-pager">
    <ul class="pagination">
        @if (Model.CurrentPage > 1)
        {
            <li>
                <a href="@Model.GetLinkForPage(Model.CurrentPage - 1)">«</a>
            </li>
        }

        @if (Model.StartDisplayedPage > 1)
        {
            <li>
                <a href="@Model.GetLinkForPage(1)">1</a>
            </li>
            if (Model.StartDisplayedPage > 2)
            {
            <li><a href="@Model.GetLinkForPage(Model.StartDisplayedPage - 1)">...</a></li>
            }
        }
        @for (int i = Model.StartDisplayedPage; i <= Model.EndDisplayedPage; i++)
        {
            if (i == Model.CurrentPage)
            {
            <li class="active"><span>@i</span></li>
            }
            else
            {
            <li><a href="@Model.GetLinkForPage(i)">@i</a></li>
            }
        }
        @if (Model.EndDisplayedPage < Model.PageCount)
        {
            if (Model.EndDisplayedPage < Model.PageCount - 1)
            {
            <li><a href="@Model.GetLinkForPage(Model.EndDisplayedPage + 1)">...</a></li>
            }
            <li><a href="@Model.GetLinkForPage(Model.PageCount)">@Model.PageCount</a></li>
        }
        @if (Model.CurrentPage < Model.PageCount)
        {
            <li><a href="@Model.GetLinkForPage(Model.CurrentPage + 1)">»</a></li>
        }
    </ul>
</div>

Mvc.Grid/Mvc.Grid/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title</title>

    <link href="~/Content/bootstrap.min.css" rel="stylesheet" />
    <script src="~/Scripts/jquery-3.5.1.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
    <script src="~/Scripts/gridmvc.js"></script>
    <link href="~/Content/Gridmvc.css" rel="stylesheet" />
</head>
<body>
    

    <div class="container body-content">

        <div class="col-md-3">

        </div>
        <div class="col-md-7">
            @RenderBody()
        </div>




      
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

  
    
</body>
</html>